default_platform(:ios)

platform :ios do
  lane :device do |options|
    device = options[:device]
    udid = options[:udid]

    register_devices(
      devices: {
        device => udid
      }
    )
  end
end
